--INICIO DE UM COMANDO PERIGOSO (UPDATE E DELETE):
BEGIN TRANSACTION;

--COMANDOS:

--EXCLUINDO OS DADOS DE UM COLABORADOR QUE FOI DESLIGADO
SELECT * FROM colaboradores WHERE ID = 3;

DELETE FROM colaboradores WHERE ID = 3;

SELECT * FROM colaboradores;

--ATUALIZANDO OS STATUS DOS PEDIDOS
UPDATE Pedidos SET Status = 'Concluído' WHERE status = 'Em Andamento';
SELECT * FROM pedidos;

--ATUALIZANDO O PREÇO DA LASANHA À BOLONHESA
UPDATE produtos SET preco = 13.0 WHERE ID = 31;

SELECT * FROM produtos;

--ATUALIZANDO A DESCRIÇÃO DO CROISSANT DE AMÊNDOA
SELECT * FROM produtos WHERE nome LIKE 'croissant%';

UPDATE produtos SET descricao = 'Croissant recheado com amêndoas.' WHERE ID = 28;

SELECT * FROM produtos;

--CASO O COMANDO DÊ ERRADO
ROLLBACK;

--CONFIRMAR O COMANDO
COMMIT;